import type { Metadata } from "next";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import ClientLayout from "@/app/clientlayout";

export const metadata: Metadata = {
  title: "Hand Mental Health",
  description: "Generated by create next app",
};

export default function TherapistLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const roleCookie = cookieStore.get("user_role");
  const role = roleCookie?.value;

  if (!role || role !== "therapist") {
    redirect("/");
  }

  return <ClientLayout>{children}</ClientLayout>;
}
